version: '3.9'

services:

  app:
    build: .
    image: university
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"