version: '3.9'

services:

  nginx:
    image: nginx:1.20.1-alpine
    ports:
      - "8989:8989"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    image: university
    deploy:
      replicas: 4
    ports:
      - "8080-8083:8080"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"