spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: university
    password: 123
    #url: ${DB_URL:jdbc:postgresql://localhost:5432/university}
    #url: ${DB_URL}
    #username: ${DB_USERNAME:university}
    #password: ${DB_PASSWORD:123}

  mvc:
    format:
      date: iso

  jpa:
    #open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE